 		   <!-- Start:Footer-->
 		 <footer>
 		 	<div id="social-links" class="aligncenter">

 		 		<!--<div class="row">
 		 			<a href="#"><i class="icon-facebook icon-circled icon-64"></i></a>
 		 			<a href="#"><i class="icon-twitter icon-circled icon-64"></i></a>
 		 		</div>-->
 		 		<div class="copyrights">
 		 			&copy;2016  All Rights Reserved.
 		 		</div>
				 
			</div>
 		 	
 		 </footer>
 		   <!-- End:Footer-->