   <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  
  <link rel="stylesheet" href="css/foundation.css" media="all" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <!--[if IE 7]>
		  <link rel="stylesheet" href="css/font-awesome-ie7.min.css">
  <![endif]-->
  <link rel="stylesheet" href="css/animate-custom.css" media="screen"/>
  <link rel="stylesheet" href="css/style.css" media="all"/>
  
  <script src="js/vendor/custom.modernizr.js"></script>
  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>          
           <link rel="stylesheet" href="css/ie8-hack.css"> 
  <![endif]-->