<nav class="top-bar" >
		                <ul class="title-area"> 
		               		<li class="name">
		                        <h1><a href="index.php" class="logo"><span>CDL Testing Inc.</span></a></h1>
		                    </li>
		                    <li class="toggle-topbar"><a href="#"><i class="icon-reorder"></i></a></li>
		                </ul> 
			            <section class="top-bar-section"> 
			                    <ul class="right">
			                    	<li><a href="index.php">Home</a></li>
			                    	<li><a href="about.php">About Us</a></li>
									<li><a href="services.php">Services</a></li> 
			                        <li><a href="cdl-testing-indianapolis-indiana.php">Indianapolis, IN</a></li>
			                        <li><a href="cdl-testing-delphi-indiana.php">Delphi, IN</a></li>
			                        <li><a href="contact.php">Contact Us</a></li>
			                    </ul> 
			            </section>
</nav>